### ISSUE TITLE
Create action for users controller

### ISSUE THREAD

**Issue by gabrielgaraujo** [ernest-phillips/debt-tracker#12]
Endpoints should accept:
first_name
last_name
email
password

If all the fields are valid and not conflicting, the endpoint should respond with 200 or 201(created) 
It should respond with the created object(user) 

When it conflicts, we should respond with error [422](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)
and an error message explaining why it failed.

**Comment by ernest-phillips** [comment]
@gabrielgaraujo here is the test I created for the Unprocessable Entity response.
I am presently getting `expected the response to have status code 422 but it was 201` 

I thought the incorrect syntax on the email would make this pass.
```
it 'responds with 422 status code' do
    post('/users', params: {user: {email: 'user@@emailcom'}})

    expect(response).to have_http_status(422)
 end
```

**Comment by gabrielgaraujo** [comment]
@ernest-phillips This should work, there is just one more adjustment, when we create the user we call `create` instead of `create!` the difference is that without bang (`!`) it does not raise errors.

- https://apidock.com/rails/v6.1.3.1/ActiveRecord/Persistence/ClassMethods/create%21
- https://apidock.com/rails/v6.1.3.1/ActiveRecord/Persistence/ClassMethods/create
