### ISSUE TITLE
Create Loan model

### ISSUE THREAD

**Issue by ernest-phillips** [ernest-phillips/debt-tracker#3]
Acceptance criteria:
- Name (mandatory)
- Creditor ref: 
- Description (optional)
- User reference : one user can have multiple accounts 
- Initial Balance
- minimum payment (in US dollars)
- Loan interest rate / Annual Percentage Rate

**Comment by gabrielgaraujo** [comment]
@ernest-phillips please, take a look at this https://github.com/ernest-phillips/debt-tracker/pull/7#discussion_r950629899 when you start working on this task
