### ISSUE TITLE
Create Creditor model

### ISSUE THREAD

**Issue by ernest-phillips** [ernest-phillips/debt-tracker#4]
Acceptance criteria:
- name -> `null: false`
- url

**Comment by gabrielgaraujo** [comment]
@ernest-phillips I believe `name` should be mandatory for this model to prevent nameless creditors.

I've updated the acceptance criteria. 

Other than that we should keep it's ticket scope small, only creating the model/migration and updating the `schema.rb`. Everything else we will handle later, controllers, routes, etc.
